### PR TITLE
[WIP] Enable IPv4 tests on Travis - fixes #22

### LINKED ISSUE #22: Don't skip IPv4 tests on Travis
As of recent, Travis VMs now have IPv4 addresses (no IPv6 though), so IPv4 tests should no longer be skipped on Travis. I did a similar thing in https://github.com/silverwind/default-gateway/commit/4e66672b7aafd7cac75bfc8210882644f8344c7e.

### PR DESCRIPTION
**Pull request by silverwind**

### CODE REVIEW

**Comment by silverwind** [comment]
Hmm, this is tricky. The CI machine have IP `10.20.0.153/32` with a gateway `10.20.0.1` outside their subnet. In a "normal" network the gateway would be within the subnet and the module currently uses this assumption. Still I think this might classify as a bug, but no idea how to resolve it cleanly besides only partially matching octets which can be inaccurate.

**Comment by silverwind** [comment]
One idea would be to return the closest matching interface IP, e.g. convert all interface IPs to numbers and take number closest to the default gateway. Thought it is still only a guess, it would work in this case.

**Comment by silverwind** [comment]
I think we could leverage `ipaddr#toByteArray` to do the number conversion, thought we can obviously not convert is to a pure JS number for IPv6 unless we want to require BigInt support.

**Comment by sindresorhus** [comment]
> thought we can obviously not convert is to a pure JS number for IPv6 unless we want to require BigInt support.

https://github.com/GoogleChromeLabs/jsbi

**Comment by sindresorhus** [comment]
Bump :)

**Comment by silverwind** [comment]
Hmm, maybe I'll have a look later using native `BigInt` (requires node 10.4+), don't want to use any of those polyfills really.

**Comment by silverwind** [comment]
Closing this in favor of https://github.com/sindresorhus/internal-ip/issues/27.

**Pull request closed without merging**
